### PR TITLE
Listen on localhost only by default

### PR DESCRIPTION
**Pull request by michaelsproul**
Prevent Prometheus and Grafana from binding to all interfaces by default

### CODE REVIEW

**Review by paulhauner — APPROVED** [review]
LGTM!

**Comment by michaelsproul** [comment]
Could also consider never binding Prometheus on 0.0.0.0, even in the public end?

**Comment by zedt3ster** [comment]
> Could also consider never binding Prometheus on 0.0.0.0, even in the public env?

I think defaulting to listening to localhost, and allowing users to explicitly expose that endpoint is good.

**Comment by michaelsproul** [comment]
Yeah, I agree. Let's merge

**Pull request merged**
